language: node_js
cache: yarn

node_js:
  - 12

jobs:
  include:
    - stage: test
      name: 'Test v12'
      node_js: 12
      script: yarn test

    - stage: deploy
      name: 'Deploy packages'
      node_js: 12
      if: (NOT type IN (pull_request)) AND (branch = master || branch = alpha || branch = beta)
      script: yarn release

    - stage: deploy
      name: 'Deploy storybook'
      if: (NOT type IN (pull_request)) AND (branch = master || branch = alpha || branch = beta)
      script: monorepo ci configure && git fetch --quiet && yarn publish:storybook

stages:
  - test
  - deploy

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
